### PR TITLE
Create V1.0.2__add_scrapable_to_bookmark.sql

### LINKED ISSUE #220: [DB] Create a migration script to add scrapable column
# Details
All of FindFirst's migration scripts are located in `/server/src/main/resources/db/migration`

## Requirements 
- [ ]  Number chronologically to the other migration scripts. For example V1.0.2__add_scrapable_to_bookmark
- [ ] Field should be a boolean

### PR DESCRIPTION
**Pull request by vijay-kesanakurthi**
Issue number: resolves #220 #221

### CODE REVIEW

**Comment by vijay-kesanakurthi** [comment]
Is it necessary to include a constructor for a property like `screenshotUrl`?

**Comment by R-Sandor** [comment]
That's a really good question, it should be included in the constructor with the screenshotUrl. 

You'll need to update the BookmarkService.java which uses that constructor to include the new parameter for scrapable. 
For the time being I would default that to true. There are some frontend tickets to look at the request field.

**Comment by vijay-kesanakurthi** [comment]
I have updated both BookmarkService and Model.

**Comment by R-Sandor** [comment]
@vijay-kesanakurthi Thanks! I appreciate all the help. Welcome to FindFirst!

**Pull request merged**
